


ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([AAMB_Curation_TYPE_PK]) REFERENCES [AAMB_CURATION_TYPE]([AAMB_Curation_TYPE_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([LIQUIDITY_PK]) REFERENCES [LIQUIDITY]([LIQUIDITY_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([Assumption_PK]) REFERENCES [ASSUMPTION]([Assumption_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([Goal_Based_Category_PK]) REFERENCES [GOAL_BASED_CATEGORY]([Goal_Based_Category_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([LDI_Category_PK]) REFERENCES [LDI_CATEGORY]([LDI_Category_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([BETA_GROUP_PK]) REFERENCES [BETA_GROUP]([BETA_GROUP_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([LIQUIDITY_PK]) REFERENCES [LIQUIDITY]([LIQUIDITY_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSET_ALLOCATION_MODELING_BENCHMARK]
	ADD  FOREIGN KEY ([AAMB_Audience_Type_PK]) REFERENCES [AAMB_AUDIENCE_TYPE]([AAMB_Audience_Type_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go






ALTER TABLE [INVESTMENT_STRUCTURE]
	ADD  FOREIGN KEY ([PLAN_PK]) REFERENCES [PLAN]([PLAN_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([PLAN_HOLDING_PK]) REFERENCES [PLAN_HOLDING]([PLAN_HOLDING_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([INVESTMENT_STRUCTURE_COMPONENT_TYPE_PK]) REFERENCES [INVESTMENT_STRUCTURE_COMPONENT_TYPE]([INVESTMENT_STRUCTURE_COMPONENT_TYPE_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([MANAGEMENT_STYLE_PK]) REFERENCES [MANAGEMENT_STYLE]([MANAGEMENT_STYLE_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([INVESTMENT_STRUCTURE_PK]) REFERENCES [INVESTMENT_STRUCTURE]([INVESTMENT_STRUCTURE_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([INVESTMENT_STRUCTURE_COMPONENT_PK]) REFERENCES [INVESTMENT_STRUCTURE_COMPONENT]([INVESTMENT_STRUCTURE_COMPONENT_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([AAMB_PK]) REFERENCES [ASSET_ALLOCATION_MODELING_BENCHMARK]([AAMB_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([Goal_Based_Category_PK]) REFERENCES [GOAL_BASED_CATEGORY]([Goal_Based_Category_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([LDI_Category_PK]) REFERENCES [LDI_CATEGORY]([LDI_Category_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([BETA_GROUP_PK]) REFERENCES [BETA_GROUP]([BETA_GROUP_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([LIQUIDITY_PK]) REFERENCES [LIQUIDITY]([LIQUIDITY_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE [MIX]
	ADD  FOREIGN KEY ([Mix_Type_PK]) REFERENCES [MIX_TYPE]([Mix_Type_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [MIX_INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([INVESTMENT_STRUCTURE_COMPONENT_PK]) REFERENCES [INVESTMENT_STRUCTURE_COMPONENT]([INVESTMENT_STRUCTURE_COMPONENT_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [MIX_INVESTMENT_STRUCTURE_COMPONENT]
	ADD  FOREIGN KEY ([MIX_PK]) REFERENCES [MIX]([MIX_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE [PLAN]
	ADD  FOREIGN KEY ([CLIENT_PK]) REFERENCES [CLIENT]([CLIENT_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [PLAN_HOLDING]
	ADD  FOREIGN KEY ([PLAN_PK]) REFERENCES [PLAN]([PLAN_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSUMPTION_VALUE_SET]
	ADD  FOREIGN KEY ([Version_PK]) REFERENCES [VERSION]([Version_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [ASSUMPTION_VALUE_SET]
	ADD  FOREIGN KEY ([Assumption_PK]) REFERENCES [ASSUMPTION]([Assumption_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [CORRELATION]
	ADD  FOREIGN KEY ([Version_PK]) REFERENCES [VERSION]([Version_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [CORRELATION]
	ADD  FOREIGN KEY ([Assumption_1_PK]) REFERENCES [ASSUMPTION]([Assumption_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [CORRELATION]
	ADD  FOREIGN KEY ([Assumption_2_PK]) REFERENCES [ASSUMPTION]([Assumption_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [DERIVED_BENCHMARK_COMPONENT]
	ADD  FOREIGN KEY ([AAMB_Allocation_PK]) REFERENCES [ASSET_ALLOCATION_MODELING_BENCHMARK]([AAMB_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [DERIVED_BENCHMARK_COMPONENT]
	ADD  FOREIGN KEY ([AAMB_Derived_Benchmark_PK]) REFERENCES [ASSET_ALLOCATION_MODELING_BENCHMARK]([AAMB_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [SCENARIO_RETURN_ASSUMPTION]
	ADD  FOREIGN KEY ([Scenario_ID_PK]) REFERENCES [SCENARIO]([Scenario_ID_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [SCENARIO_RETURN_ASSUMPTION]
	ADD  FOREIGN KEY ([Assumption_PK]) REFERENCES [ASSUMPTION]([Assumption_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [SCENARIO_RETURN_ASSUMPTION]
	ADD  FOREIGN KEY ([Version_PK]) REFERENCES [VERSION]([Version_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [SCENARIO_RETURN_ASSUMPTION]
	ADD  FOREIGN KEY ([ASSUMPTION_TYPE_PK]) REFERENCES [ASSUMPTION_TYPE]([ASSUMPTION_TYPE_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [TAX_RATE]
	ADD  FOREIGN KEY ([Tax_Jurisdiction_PK]) REFERENCES [dbo].[TAX_JURISDICTION]([Tax_Jurisdiction_PK])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
