#=======================================================================================================================
#== SPRING =============================================================================================================
#=======================================================================================================================

server.port: 9087

logging:
  file: logs/asset-manager.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.nepc: DEBUG

#=======================================================================================================================
#== SPRING JPA =========================================================================================================
#=======================================================================================================================

spring.datasource:
  url: jdbc:sqlserver://localhost;databaseName=asset_allocation_v2
  username: NEPCUser
  password: Admin@123#
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
