#=======================================================================================================================
#== GENERAL CONFIGURATION ==============================================================================================
#=======================================================================================================================

asset.manager.pulse.threshold: 5
asset.manager.pulse.maxAge: 90000
# asset.manager.baseHref: /asset-manager-webapp

#=======================================================================================================================
#== SPRING =============================================================================================================
#=======================================================================================================================

spring.profiles.active: default,local-sql-server

server.port: 8080
# server.contextPath: /asset-manager-webapp

logging:
  pattern:
    console: "%msg%n"
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.nepc: DEBUG

#=======================================================================================================================
#== SPRING SECURITY ====================================================================================================
#=======================================================================================================================

security.basic.enabled: false
management.security.enabled: false

#=======================================================================================================================
#== SPRING JPA =========================================================================================================
#=======================================================================================================================

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
