server:
  port: 8080
  # contextPath: /asset-manager-webapp

spring.profiles.active: local,default

spring:
logging:
  pattern:
    console: "%msg%n"
  level:
    org.springframework.web: INFO
    com.sigma.eduko.endpoint: INFO
    org.hibernate: INFO


