#=======================================================================================================================
#== SPRING JPA =========================================================================================================
#=======================================================================================================================

spring:
  datasource:
    url: jdbc:h2:mem:AADB-LOCAL;MODE=MSSQLServer # H2 in SQL Server mode
  h2:
    console:
      enabled: true
      path: /h2-console
