#=======================================================================================================================
#== SPRING JPA =========================================================================================================
#=======================================================================================================================

spring.datasource:
  url: jdbc:sqlserver://localhost;databaseName=asset_allocation_v2
  username: NEPCUser
  password: Admin@123#
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
