server:
  port: 9087

spring:
logging:
  file: logs/asset-manager.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring.profiles: dev

spring.datasource.url: jdbc:sqlserver://localhost;databaseName=asset_allocation_v2
spring.datasource.username: NEPCUser
spring.datasource.password: Admin@123#
spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 50
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


